name: Test JS Project

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:20
    steps:
      - uses: actions/checkout@v5
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: './front/package-lock.json'
      - run: npm ci
      - run: npm test
      - run: npm run build
